language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - source

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $leetcode
  local_dir: public
  on:
    branch: master