language: node_js
node_js: stable
branches:
    only:
        - source

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - hexo clean
    - hexo g

after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "rhsphere"
    - git config user.email "rhsphere@gmail.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${leetcode}@${GH_REF}" master:master

env:
    global:
        - GH_REF: git@github.com:rhSphere/leetcode.git




  